package org.yccheok.blobsallad.demo;

import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

import org.yccheok.blobsallad.Controller;

/**
 */
public class BlobsalladApplicationDemo extends JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Controller controller = new Controller();

	/** Creates new form BlobsalladApplicationDemo */
	public BlobsalladApplicationDemo() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jPanel2 = new JPanel();
		jLabel1 = new JLabel();
		jPanel1 = controller.getView();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		setTitle("blobsallad");
		setResizable(false);

		jPanel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
		jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
		jLabel1
				.setText("<html>\nMove around Blob with arrow keys or mouse.\n</html>");
		jPanel2.add(jLabel1);

		getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

		GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGap(0, 579, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGap(0, 399, Short.MAX_VALUE));

		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		setBounds((screenSize.width - 595) / 2, (screenSize.height - 565) / 2,
				595, 565);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BlobsalladApplicationDemo().setVisible(true);
			}
		});
	}

	private JLabel jLabel1;
	private JPanel jPanel1;
	private JPanel jPanel2;

}
