package missiontimer;

import javax.swing.JFrame;
import javax.swing.WindowConstants;

import swinglayout.GroupLayout;

/**
 *
 */
public class MissionTimerTest extends JFrame {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form Main */
	public MissionTimerTest() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		timerPanel1 = new MissionTimerPanel();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		setTitle("Apollo Mission Timer");
		setResizable(false);

		timerPanel1.setName("timerPanel1"); // NOI18N

		GroupLayout timerPanel1Layout = new GroupLayout(timerPanel1);
		timerPanel1.setLayout(timerPanel1Layout);
		timerPanel1Layout.setHorizontalGroup(timerPanel1Layout
				.createParallelGroup(GroupLayout.LEADING).add(0, 450,
						Short.MAX_VALUE));
		timerPanel1Layout.setVerticalGroup(timerPanel1Layout
				.createParallelGroup(GroupLayout.LEADING).add(0, 180,
						Short.MAX_VALUE));

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				GroupLayout.LEADING).add(timerPanel1,
				GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
				GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.LEADING)
				.add(timerPanel1, GroupLayout.PREFERRED_SIZE,
						GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				MissionTimerTest app = new MissionTimerTest();
				app.setLocationRelativeTo(null);
				app.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private missiontimer.MissionTimerPanel timerPanel1;
	// End of variables declaration//GEN-END:variables
}
