/*
 * DemoFrame.java
 *
 * Created on 2007年6月24日, 上午12:24
 */

package clickeffect;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JToggleButton;
import javax.swing.UIManager;
import javax.swing.WindowConstants;

import clickingeffect.ClickingEffectPane;

/**
 */
public class DemoFrame extends JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form DemoFrame */
	public DemoFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		clickingEffectPane1 = new ClickingEffectPane();
		jLabel1 = new JLabel();
		jButton1 = new JButton();
		jToggleButton1 = new JToggleButton();
		jCheckBox1 = new JCheckBox();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		clickingEffectPane1.setBorder(BorderFactory.createEtchedBorder());
		jLabel1
				.setText("<html> <body> <h4>Welcome to swing demo program!</h4> <ul> <li>Click any where of the panel to see the clicking effect.</li> <li>You can also click any subcomponents of the panel.</li> \n<li>You can change the clicking effect to any <p>other effect by implementing Animator interface.</li>\n</ul> <em><strong>Enjoy swing programming!</strong></em> </body> </html>");

		jButton1.setText("Click me");
		jButton1.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				System.out.println(123);
			}
		});

		jToggleButton1.setText("Toggle me");

		jCheckBox1.setText("Check me");
		jCheckBox1.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));

		GroupLayout clickingEffectPane1Layout = new GroupLayout(
				clickingEffectPane1);
		clickingEffectPane1.setLayout(clickingEffectPane1Layout);

		clickingEffectPane1.setLayout(new FlowLayout());
		clickingEffectPane1.add(jLabel1);
		clickingEffectPane1.add(jButton1);
		clickingEffectPane1.add(jToggleButton1);
		clickingEffectPane1.add(jCheckBox1);

		getContentPane().setLayout(new BorderLayout());
		getContentPane().add(clickingEffectPane1, BorderLayout.CENTER);

		pack();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			System.setProperty("swing.useSystemFontSettings", "false");
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (Exception ex) {
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DemoFrame().setVisible(true);
			}
		});
	}

	private ClickingEffectPane clickingEffectPane1;
	private JButton jButton1;
	private JCheckBox jCheckBox1;
	private JLabel jLabel1;
	private JToggleButton jToggleButton1;
}
