/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SDOptionPanel.java
 *
 * Created on 01.11.2009, 13:26:33
 */

package de.jugms.sd.components.panels;

/**
 *
 * @author hansolo
 */
public class SDOptionPanel extends javax.swing.JPanel {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    /** Creates new form SDOptionPanel */
    public SDOptionPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupColor = new javax.swing.ButtonGroup();
        buttonGroupRadiusType = new javax.swing.ButtonGroup();
        sDLinearGradientPanel1 = new de.jugms.sd.components.panels.SDLinearGradientPanel();
        radioButtonBlue = new de.jugms.sd.components.buttons.SDRadioButton();
        radioButtonRed = new de.jugms.sd.components.buttons.SDRadioButton();
        radioButtonOrange = new de.jugms.sd.components.buttons.SDRadioButton();
        radioButtonYellow = new de.jugms.sd.components.buttons.SDRadioButton();
        radioButtonGreen = new de.jugms.sd.components.buttons.SDRadioButton();
        radioButtonGray = new de.jugms.sd.components.buttons.SDRadioButton();
        checkBoxTranslucent = new de.jugms.sd.components.buttons.SDCheckBox();
        checkBoxReflection = new de.jugms.sd.components.buttons.SDCheckBox();
        radioButtonSharp = new de.jugms.sd.components.buttons.SDRadioButton();
        radioButtonRounded = new de.jugms.sd.components.buttons.SDRadioButton();
        radioButtonPill = new de.jugms.sd.components.buttons.SDRadioButton();

        sDLinearGradientPanel1.setName("sDLinearGradientPanel1"); // NOI18N

        buttonGroupColor.add(radioButtonBlue);
        radioButtonBlue.setSelected(true);
        radioButtonBlue.setText("blue");
        radioButtonBlue.setName("radioButtonBlue"); // NOI18N

        buttonGroupColor.add(radioButtonRed);
        radioButtonRed.setText("red");
        radioButtonRed.setName("radioButtonRed"); // NOI18N

        buttonGroupColor.add(radioButtonOrange);
        radioButtonOrange.setText("orange");
        radioButtonOrange.setName("radioButtonOrange"); // NOI18N

        buttonGroupColor.add(radioButtonYellow);
        radioButtonYellow.setText("yellow");
        radioButtonYellow.setName("radioButtonYellow"); // NOI18N

        buttonGroupColor.add(radioButtonGreen);
        radioButtonGreen.setText("green");
        radioButtonGreen.setName("radioButtonGreen"); // NOI18N

        buttonGroupColor.add(radioButtonGray);
        radioButtonGray.setText("gray");
        radioButtonGray.setName("radioButtonGray"); // NOI18N

        checkBoxTranslucent.setText("Translucent");
        checkBoxTranslucent.setName("checkBoxTranslucent"); // NOI18N

        checkBoxReflection.setText("Reflection");
        checkBoxReflection.setName("checkBoxReflection"); // NOI18N

        buttonGroupRadiusType.add(radioButtonSharp);
        radioButtonSharp.setText("Rectangluar");
        radioButtonSharp.setName("radioButtonSharp"); // NOI18N

        buttonGroupRadiusType.add(radioButtonRounded);
        radioButtonRounded.setSelected(true);
        radioButtonRounded.setText("Rounded rectangle");
        radioButtonRounded.setName("radioButtonRounded"); // NOI18N

        buttonGroupRadiusType.add(radioButtonPill);
        radioButtonPill.setText("Pill");
        radioButtonPill.setName("radioButtonPill"); // NOI18N

        javax.swing.GroupLayout sDLinearGradientPanel1Layout = new javax.swing.GroupLayout(sDLinearGradientPanel1);
        sDLinearGradientPanel1.setLayout(sDLinearGradientPanel1Layout);
        sDLinearGradientPanel1Layout.setHorizontalGroup(
            sDLinearGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sDLinearGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sDLinearGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radioButtonBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonYellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonGray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxTranslucent, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(sDLinearGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonSharp, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonPill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonRounded, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxReflection, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap())
        );
        sDLinearGradientPanel1Layout.setVerticalGroup(
            sDLinearGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sDLinearGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sDLinearGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonSharp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sDLinearGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonRounded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sDLinearGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonPill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonYellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonGray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sDLinearGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxTranslucent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxReflection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sDLinearGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sDLinearGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupColor;
    private javax.swing.ButtonGroup buttonGroupRadiusType;
    public de.jugms.sd.components.buttons.SDCheckBox checkBoxReflection;
    public de.jugms.sd.components.buttons.SDCheckBox checkBoxTranslucent;
    public de.jugms.sd.components.buttons.SDRadioButton radioButtonBlue;
    public de.jugms.sd.components.buttons.SDRadioButton radioButtonGray;
    public de.jugms.sd.components.buttons.SDRadioButton radioButtonGreen;
    public de.jugms.sd.components.buttons.SDRadioButton radioButtonOrange;
    public de.jugms.sd.components.buttons.SDRadioButton radioButtonPill;
    public de.jugms.sd.components.buttons.SDRadioButton radioButtonRed;
    public de.jugms.sd.components.buttons.SDRadioButton radioButtonRounded;
    public de.jugms.sd.components.buttons.SDRadioButton radioButtonSharp;
    public de.jugms.sd.components.buttons.SDRadioButton radioButtonYellow;
    private de.jugms.sd.components.panels.SDLinearGradientPanel sDLinearGradientPanel1;
    // End of variables declaration//GEN-END:variables

}
