/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SDInputPanel.java
 *
 * Created on 16.09.2009, 20:39:36
 */
package de.jugms.sd.components.panels;

/**
 * 
 * @author hansolo
 */
public class SDTestInputPanel extends javax.swing.JPanel {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /** Creates new form SDInputPanel */
    public SDTestInputPanel() {
        initComponents();
        textPaneComment.setDefaultText("comment...");
        setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(0, 0, 0, 0)));
        progressBar.setTilted(true);
    }

    @Override
    public String toString() {
        return "SDInputPanel";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupContact = new javax.swing.ButtonGroup();
        cancelButton = new de.jugms.sd.components.buttons.SDButton();
        submitButton = new de.jugms.sd.components.buttons.SDButton();
        radioButtonPhone = new de.jugms.sd.components.buttons.SDRadioButton();
        radioButtonMail = new de.jugms.sd.components.buttons.SDRadioButton();
        textFieldMail = new de.jugms.sd.components.textfields.SDTextField();
        textFieldMail.setForeground(new java.awt.Color(1.0f, 1.0f, 1.0f, 0.6f));
        textFieldPhone = new de.jugms.sd.components.textfields.SDTextField();
        textFieldPhone.setForeground(new java.awt.Color(1.0f, 1.0f, 1.0f, 0.6f));
        textFieldSubject = new de.jugms.sd.components.textfields.SDTextField();
        textFieldSubject.setForeground(new java.awt.Color(1.0f, 1.0f, 1.0f, 0.6f));
        textFieldFirstName = new de.jugms.sd.components.textfields.SDTextField();
        textFieldFirstName.setForeground(new java.awt.Color(1.0f, 1.0f, 1.0f, 0.6f));
        textFieldLastName = new de.jugms.sd.components.textfields.SDTextField();
        textFieldLastName.setForeground(new java.awt.Color(1.0f, 1.0f, 1.0f, 0.6f));
        progressBar = new de.jugms.sd.components.misc.SDGlassProgressBar();
        comboBoxTitle = new de.jugms.sd.components.comboboxes.SDComboBox();
        comboBoxAge = new de.jugms.sd.components.comboboxes.SDComboBox();
        textPaneComment = new de.jugms.sd.components.misc.SDTextPane1();
        sDCheckBox1 = new de.jugms.sd.components.buttons.SDCheckBox();

        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        setOpaque(false);

        cancelButton.setText("Cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(86, 22));
        cancelButton.setMinimumSize(new java.awt.Dimension(86, 22));
        cancelButton.setName("cancelButton"); // NOI18N

        submitButton.setText("Submit");
        submitButton.setEnabled(false);
        submitButton.setMaximumSize(new java.awt.Dimension(88, 25));
        submitButton.setMinimumSize(new java.awt.Dimension(88, 25));
        submitButton.setName("submitButton"); // NOI18N

        buttonGroupContact.add(radioButtonPhone);
        radioButtonPhone.setEnabled(false);
        radioButtonPhone.setName("radioButtonPhone"); // NOI18N

        buttonGroupContact.add(radioButtonMail);
        radioButtonMail.setSelected(true);
        radioButtonMail.setName("radioButtonMail"); // NOI18N

        textFieldMail.setToolTipText("e.g. \"luke.skywalker@alliance.net");
        textFieldMail.setName("textFieldMail"); // NOI18N

        textFieldPhone.setToolTipText("e.g. \"+49 1802 100101\"");
        textFieldPhone.setName("textFieldPhone"); // NOI18N
        textFieldPhone.setType(de.jugms.sd.components.textfields.SDTextField.ICON_TYPE.PHONE);

        textFieldSubject.setToolTipText("e.g. \"The force\"");
        textFieldSubject.setName("textFieldSubject"); // NOI18N
        textFieldSubject.setType(de.jugms.sd.components.textfields.SDTextField.ICON_TYPE.PEN);

        textFieldFirstName.setToolTipText("e.g. \"Skywalker\"");
        textFieldFirstName.setDefaultText("last name");
        textFieldFirstName.setName("textFieldFirstName"); // NOI18N
        textFieldFirstName.setType(de.jugms.sd.components.textfields.SDTextField.ICON_TYPE.NO_ICON);

        textFieldLastName.setToolTipText("e.g. \"Luke\"");
        textFieldLastName.setDefaultText("first name");
        textFieldLastName.setName("textFieldLastName"); // NOI18N
        textFieldLastName.setType(de.jugms.sd.components.textfields.SDTextField.ICON_TYPE.NO_ICON);

        progressBar.setInfiniteText("submission");
        progressBar.setName("progressBar"); // NOI18N
        progressBar.setShowInfiniteText(true);

        javax.swing.GroupLayout progressBarLayout = new javax.swing.GroupLayout(progressBar);
        progressBar.setLayout(progressBarLayout);
        progressBarLayout.setHorizontalGroup(progressBarLayout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 127, Short.MAX_VALUE));
        progressBarLayout.setVerticalGroup(progressBarLayout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 22, Short.MAX_VALUE));

        comboBoxTitle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "title", "Mr.",
                "Mrs.", "Dr.", "Prof." }));
        comboBoxTitle.setName("comboBoxTitle"); // NOI18N
        comboBoxTitle.setPreferredSize(new java.awt.Dimension(174, 22));

        comboBoxAge.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "age",
                "< 20 years", "21 - 30 years", "31 - 40 years", "41 - 50 years", "> 50 years" }));
        comboBoxAge.setName("comboBoxAge"); // NOI18N
        comboBoxAge.setPreferredSize(new java.awt.Dimension(174, 22));

        textPaneComment.setName("textPaneComment"); // NOI18N

        sDCheckBox1.setText("Contact me by");
        sDCheckBox1.setName("sDCheckBox1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout
                .setHorizontalGroup(layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                layout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                sDCheckBox1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                239,
                                                                                Short.MAX_VALUE)
                                                                        .addGap(88, 88, 88))
                                                        .addComponent(
                                                                textPaneComment,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                327, Short.MAX_VALUE)
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                layout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                cancelButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(
                                                                                progressBar,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                127,
                                                                                Short.MAX_VALUE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(
                                                                                submitButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(
                                                                textFieldSubject,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                327, Short.MAX_VALUE)
                                                        .addGroup(
                                                                layout
                                                                        .createSequentialGroup()
                                                                        .addGroup(
                                                                                layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(
                                                                                                textFieldMail,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                300,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(
                                                                                                textFieldPhone,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                300,
                                                                                                Short.MAX_VALUE))
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addGroup(
                                                                                layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(
                                                                                                radioButtonPhone,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                19,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(
                                                                                                radioButtonMail,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                21,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(
                                                                textFieldLastName,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                327, Short.MAX_VALUE)
                                                        .addComponent(
                                                                textFieldFirstName,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                327, Short.MAX_VALUE)
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                layout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                comboBoxTitle,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                135,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(
                                                                                comboBoxAge,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)))
                                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap().addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboBoxTitle,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                        javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(
                                        comboBoxAge, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                        textFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                        textFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addComponent(
                        sDCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 17,
                        javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                false).addComponent(radioButtonMail,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFieldMail,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(
                                        layout.createSequentialGroup().addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldPhone,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(
                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                        layout.createSequentialGroup().addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(radioButtonPhone,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18).addComponent(textFieldSubject,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                                javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                                textPaneComment, javax.swing.GroupLayout.DEFAULT_SIZE, 99,
                                Short.MAX_VALUE).addGap(18, 18, 18).addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.TRAILING).addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cancelButton,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE).addComponent(submitButton,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(progressBar,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupContact;
    public de.jugms.sd.components.buttons.SDButton cancelButton;
    public de.jugms.sd.components.comboboxes.SDComboBox comboBoxAge;
    public de.jugms.sd.components.comboboxes.SDComboBox comboBoxTitle;
    public de.jugms.sd.components.misc.SDGlassProgressBar progressBar;
    public de.jugms.sd.components.buttons.SDRadioButton radioButtonMail;
    public de.jugms.sd.components.buttons.SDRadioButton radioButtonPhone;
    private de.jugms.sd.components.buttons.SDCheckBox sDCheckBox1;
    public de.jugms.sd.components.buttons.SDButton submitButton;
    public de.jugms.sd.components.textfields.SDTextField textFieldFirstName;
    public de.jugms.sd.components.textfields.SDTextField textFieldLastName;
    public de.jugms.sd.components.textfields.SDTextField textFieldMail;
    public de.jugms.sd.components.textfields.SDTextField textFieldPhone;
    public de.jugms.sd.components.textfields.SDTextField textFieldSubject;
    public de.jugms.sd.components.misc.SDTextPane1 textPaneComment;
    // End of variables declaration//GEN-END:variables
}
